######################################################################
# Automatically generated by qmake (2.01a) Fri 11. Jun 17:55:22 2021
######################################################################

CC = cl
CXX = cl /clr 
CONFIG = console foo
SHELL = cmd
MAKE = nmake
TEMPLATE = app
TARGET = qtc-msvc2008
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += frooler.h squibber.h
SOURCES += foo.cpp frooler.cpp squibber.cpp
