######################################################################
# Automatically generated by qmake (2.01a) Fri 4. Jun 12:10:08 2021
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += frooler.h squibber.h
SOURCES += foo.cpp frooler.cpp squibber.cpp
